---
- name: Add PostgreSQL package repository
  tags: setup
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main

- name: Add PostgreSQL package repository key
  tags: setup
  apt_key:
    id: ACCC4CF8
    url: http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc

- name: Updating package sources
  tags: setup
  apt: update_cache=yes

- name: Installing PostgreSQL packages
  tags: setup
  apt: name={{item}} state=latest
  with_items:
    - python-psycopg2
    - postgresql-{{postgresql_version}}
    - libpq-dev
    - postgresql-contrib-{{postgresql_version}}
    - pgtune
    - ptop

- name: Installing PostGIS packages
  tags: setup
  apt: name=postgresql-{{postgresql_version}}-postgis-scripts state=latest
  when: postgresql_install_postgis

- name: Backup PostgreSQL config
  tags: setup
  command: mv {{postgresql_config_path}} {{postgresql_config_path}}.old creates={{postgresql_config_path}}.old

- name: Run pgtune against PostgreSQL config
  tags: setup
  command: pgtune -i {{postgresql_config_path}}.old -o {{postgresql_config_path}} --type=Web
  sudo: yes
  sudo_user: postgres

- name: Set bound IP
  tags: config
  lineinfile:
    dest: '{{postgresql_config_path}}'
    line: 'listen_addresses = ''localhost,{{postgresql_bind}}'''
    regexp: ^listen_addresses
  when: postgresql_bind is defined

- name: Get _PHYS_PAGES
  tags: config
  shell: getconf _PHYS_PAGES
  register: phys_pages_result

- name: Get PAGE_SIZE
  tags: config
  shell: getconf PAGE_SIZE
  register: page_size_result

- name: Get total pages
  tags: config
  shell: expr {{phys_pages_result.stdout}} / 2
  register: kernel_shmmax_result

- name: Get memory page size
  tags: config
  shell: expr {{kernel_shmmax_result.stdout}} \* {{page_size_result.stdout}}
  register: kernel_shmall_result

- name: Configure shared memory for PostgreSQL
  tags: config
  sysctl: name={{item.key}} value={{item.value}} state=present reload=yes
  with_dict:
    kernel.shmmax: '{{kernel_shmmax_result.stdout}}'
    kernel.shmall: '{{kernel_shmall_result.stdout}}'
  notify: Restart PostgreSQL

- name: Enable PostgreSQL service
  tags: setup
  service: name=postgresql enabled=yes state=restarted
