---
- name: Set FQDN
  lineinfile:
    dest: /etc/hosts
    line: '127.0.1.1 {{fqdn}} {{hostname}}'
    regexp: ^127.0.1.1
    state: present

- name: Configure static interfaces
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
