---
- name: Install Redis dependent packages
  tags: setup
  apt: name={{item}} state=latest
  with_items:
    - make
    - build-essential
    - tcl8.5

- name: Install 32bit Redis dependent packages
  tags: setup
  apt: name=libc6-dev-i386 state=latest
  when: ansible_userspace_bits == "32"

- name: Download Redis {{redis_version}}
  tags: setup
  get_url:
    url: http://download.redis.io/releases/redis-{{redis_version}}.tar.gz
    dest: /tmp/redis-{{redis_version}}.tgz
    force: yes

- name: Extract Redis
  tags: setup
  unarchive: copy=no src=/tmp/redis-{{redis_version}}.tgz dest=/tmp/

- name: Compile Redis (64bit)
  tags: setup
  command: make -C /tmp/redis-{{redis_version}} creates=/tmp/redis-{{redis_version}}/src/redis-server
  when: ansible_userspace_bits == "64"

- name: Compile Redis (32bit)
  tags: setup
  command: make 32bit -C /tmp/redis-{{redis_version}} creates=/tmp/redis-{{redis_version}}/src/redis-server
  when: ansible_userspace_bits == "32"

- name: Install Redis
  tags: setup
  command: make install -C /tmp/redis-{{redis_version}}

- name: Add Redis group
  tags: setup
  group: name={{redis_group}} system=yes state=present

- name: Add Redis user
  tags: setup
  user: name={{redis_group}} group={{redis_group}} system=yes state=present

- name: Create Redis data directory
  tags: setup
  file:
    path: '{{redis_data_directory}}'
    state: directory
    mode: '0755'
    group: '{{redis_group}}'
    owner: '{{redis_user}}'

- name: Create Redis log directory
  tags: setup
  file:
    path: '{{redis_log_directory}}'
    state: directory
    mode: '0755'
    group: '{{redis_group}}'
    owner: root

- name: Create Redis logfile
  tags: setup
  file:
    path: '{{redis_log_directory}}/{{redis_log_file}}'
    state: touch
    owner: '{{redis_user}}'
    group: '{{redis_group}}'
    mode: '0644'

- name: Add Redis logrotate script
  tags: setup
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/redis
    owner: root
    group: root
    mode: '0644'

- name: Add Redis Upstart script
  tags: setup
  template: src=upstart.j2 dest=/etc/init/redis.conf

- name: Add Redis configuration file
  tags: config
  template:
    src: redis.conf.j2
    dest: '{{redis_conf}}'
    group: '{{redis_group}}'
    owner: '{{redis_user}}'
  notify: Restart Redis

- name: Clean up
  tags: setup
  file: path=/tmp/{{item}} state=absent
  with_items:
    - redis-{{redis_version}}
    - redis-{{redis_version}}.tgz

- name: Enable Redis service
  tags: setup
  service: name=redis enabled=yes state=restarted
