---
- name: Add Nginx package repository
  tags: setup
  apt_repository: repo=ppa:nginx/stable

- name: Install Nginx
  tags: setup
  apt: name=nginx-full state=latest update_cache=yes

- name: Remove Nginx default enabled site
  tags: setup
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Remove Nginx default site
  tags: setup
  file: path=/etc/nginx/sites-available/default state=absent

- name: Remove Nginx default configuration
  tags: setup
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: Remove default Nginx root configuration
  tags: setup
  file: path=/etc/nginx/nginx.conf state=absent

- name: Add new Nginx root configuration
  tags: config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Ensure Nginx directories are created
  tags: setup
  file: path=/etc/nginx/{{item}} state=directory
  with_items:
    - sites-available
    - sites-enabled

- name: Add Nginx configurations
  tags: config
  template: src=conf/{{item}}.j2 dest=/etc/nginx/conf.d/{{item}}
  with_items:
    - gzip.conf
    - mimes.conf
  notify: Restart Nginx

- name: Enable Nginx service
  tags: setup
  service: name=nginx enabled=yes state=restarted
