---
- name: Create root data directory
  file: path={{deploy_data_directory}} state=directory

- name: Add {{deploy_user}} user
  user: name={{deploy_user}} shell=/bin/bash

- name: Download authorized keys from GitHub for {{deploy_user}}
  connection: local
  get_url:
    src: https://github.com/{{item}}.keys
    dest: /tmp/github.{{item}}.keys
  with_items: '{{deploy_authorized_githubbers}}'

- name: Install authorized keys for {{deploy_user}}
  authorized_key:
    user: '{{deploy_user}}'
    key: "{{lookup('file', '/tmp/github.' + item + '.keys')}}"
  with_items: '{{deploy_authorized_githubbers}}'
