# This will provision a cold Linode into a full-stack web server, which just
# means a web server that has everything on it, database, app server, nginx,
# workers.
---
- name: Provision Full-Stack servers
  hosts: fullstack

  vars:
    private_netmask: 255.255.128.0 # DigitalOcean is 255.255.0.0
    public_netmask: 255.255.255.0 # DigitalOcean is 255.255.240.0
    postgresql_version: 9.3
    nginx_max_connections: 2000
    redis_bind: 127.0.0.1

  vars_prompt:
    - name: admin_password
      prompt: 'Enter password for {{admin_user}}'
      private: yes

  roles:
    - vps
    - redis
    - database
    - rvm_app_puma
    - rvm_app_sidekiq
    - nodejs

  post_tasks:
    - name: Allow HTTP traffic
      ufw: rule=allow port=80 state=enabled proto=tcp

    - name: Allow HTTPS traffic
      ufw: rule=allow port=443 state=enabled proto=tcp

    - name: Restart VPS
      command: 'shutdown -r now "System has been provisioned"'
      ignore_errors: yes
