---
- name: Gather facts from all servers
  hosts: all

- name: Provision Full-Stack servers
  hosts: fullstackservers

  vars:
    postgresql_version: 9.3
    nginx_max_connections: 2000
    redis_bind: 127.0.0.1

  vars_prompt:
    - name: admin_password
      prompt 'Enter password for {{admin_user}}'
      private: yes

  roles:
    - vps
    - redis
    - database
    - rvm_app_puma
    - rvm_app_sidekiq
    - nodejs

  post_tasks:
    - name: Allow HTTP traffic
      ufw: rule=allow port=80 state=enabled proto=tcp

    - name: Allow HTTPS traffic
      ufw: rule=allow port=443 state=enabled proto=tcp

    - name: Restart VPS
      command: 'shutdown -r now "System has been provisioned"'
      ignore_errors: yes
