# This playbook is for provisioning cold servers, for example. If you create
# a new Linode, deploy Ubuntu to it, and boot it, this will be the next step.
---
- name: Provision Full-Stack servers
  hosts: everything_servers

  roles:
    - { name: 'redis', tags: 'redis' }
    - { name: 'database', tags: 'database' }
    - { name: 'rvm_app_puma', tags: 'puma' }
    - { name: 'rvm_app_sidekiq', tags: 'sidekiq' }
    - { name: 'nodejs', tags: 'nodejs' }

- name: Provision database servers
  hosts: db_servers

  vars_prompt:
    - name: admin_password
      prompt: 'Enter password for {{admin_user}}'
      private: yes

  roles:
    - vps
    - { name: 'redis', tags: 'redis' }
    - { name: 'database', tags: 'database' }

- name: Provision application servers
  hosts: app_servers

- name: Provision worker servers
  hosts: worker_servers
