---
- name: Provision a Vagrant VM with RVM, Redis, Postgres, Node.js, and Nginx
  hosts: all
  remote_user: vagrant
  gather_facts: yes
  sudo: yes

  vars:
    - hostname: vagrant
    - rvm_ruby_version: 2.1.2
    - rvm_install_user: vagrant
    - postgresql_version: 9.3
    - vagrant_user: vagrant
    - vagrant_data_directory: /vagrant
    - nginx_max_connections: 100

  roles:
    - essential_system
    - rvm
    - nodejs
    - postgresql
    - redis
    - nginx
    - vagrant_nginx
    - vagrant_postgresql
    - vagrant_helpful
