---
- name: Set /etc/localtime to {{timezone}}
  copy: src=/usr/share/zoneinfo/{{timezone}} dest=/etc/localtime owner=root group=root mode=0644 backup=yes
  tags: set_etc_localtime

- name: Set /etc/timezone to {{timezone}}
  template: dest=/etc/timezone src=timezone.j2
  notify: Update tzdata
  tags: set_etc_timezone
