---
- name: Generate locale
  locale_gen: name={{system_locale}} state=present
  tags: generate_local

- name: Set locale
  shell: update-locale LANG={{system_locale}} LC_MESSAGES={{system_locale}} LC_ALL={{system_locale}}
  tags: set_locale
