---
app_user: deploy
app_group: deploy
app_authorized_githubbers: []
app_data_directory: /sites
app_domain:
app_env: production
app_ident: '{{app_domain|replace(''.'', ''-'')}}'
app_directory: '{{app_data_directory}}/{{app_domain}}'
app_current_directory: '{{app_directory}}/current'
app_releases_directory: '{{app_directory}}/releases'
app_repo_directory: '{{app_directory}}/repo'
app_shared_directory: '{{app_directory}}/shared'
app_shared_log_directory: '{{app_shared_directory}}/log'
app_shared_tmp_directory: '{{app_shared_directory}}/tmp'
app_shared_config_directory: '{{app_shared_directory}}/config'
app_shared_bin_directory: '{{app_shared_directory}}/bin'
app_shared_bundle_directory: '{{app_shared_directory}}/bundle'
app_shared_sockets_directory: '{{app_shared_directory}}/sockets'
app_database_name: '{{database_name}}'
app_database_adapter: postgresql
app_database_encoding: unicode
app_database_user: '{{database_user}}'
app_database_host: '{{hostvars[groups.db_servers.0].private_ip}}'
app_database_pool: 35
app_secrets: {}
