---
- name: Update apt package sources
  apt: update_cache=yes cache_valid_time={{system_apt_cache_ttl}}
  tags: essential_system_update

- name: Upgrade installed packages
  apt: upgrade=safe
  tags: essential_system_upgrade

- name: Install essential packages
  apt: name={{item}} state=latest
  with_items:
    - curl
    - vim-nox
    - less
    - htop
    - git-core
    - tree
    - python-software-properties
  tags: essential_system_install
