---
- name: Update apt package sources
  apt: update_cache=yes cache_valid_time={{system_apt_cache_ttl}}

- name: Upgrade installed packages
  apt: upgrade=safe

- name: Install packages
  apt: name={{item}} state=latest
  with_items:
    - curl
    - vim-nox
    - less
    - htop
    - git-core
    - tree
    - python-software-properties
