---
- name: Update sources and upgrade packages
  apt: upgrade=safe update_cache=yes cache_valid_time={{system_apt_cache_ttl}}

- name: Install base packages
  apt: name={{item}} state=latest
  with_items: '{{essential_packages}}'

- name: Generate locale {{locale}}
  locale_gen: name={{locale}} state=present

- name: Set locale to {{locale}}
  shell: |
    update-locale \
      LANG={{locale}} \
      LC_MESSAGES={{locale}} \
      LC_ALL={{locale}} \
      LC_COLLATE={{locale}} \
      LC_CTYPE={{locale}}

- name: Install NTP
  apt: name=ntp state=latest

- name: Enable NTP
  service: name=ntp state=started enabled=yes

- name: Setting timezone in /etc/localtime to {{timezone}}
  copy:
    src: /usr/share/zoneinfo/{{timezone}}
    dest: /etc/localtime
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Setting timezone in /etc/timezone to {{timezone}}
  template: dest=/etc/timezone src=timezone.j2
  notify: Update tzdata
