---
- name: Update sources and upgrade packages
  apt: upgrade=safe update_cache=yes cache_valid_time={{system_apt_cache_ttl}}

- name: Install packages
  apt: name={{item}} state=latest
  with_items:
    - curl
    - vim-nox
    - less
    - htop
    - git-core
    - tree
    - python-software-properties
