---
puma_config_relative_path: config/puma.rb
puma_pid_path: '{{app_shared_tmp_directory}}/pids/puma.pid'
puma_socket_path: '{{app_shared_sockets_directory}}/puma.sock'
puma_state_directory: '{{app_shared_tmp_directory}}/puma'

puma_init_reload_with_phased_restart: no
puma_init_ident: '{{app_ident}}-puma'

puma_nginx_additional_server_names: []
puma_nginx_fonts_origin: enforce
puma_nginx_redirect_www: yes
puma_nginx_enable_gzip_static_assets: yes
puma_nginx_assets_directory_name: assets

puma_logrotate_event: weekly
puma_logrotate_maxrotations: 52
