---
- name: Install (UFW)
  apt: name=ufw state=latest

- name: Configure defaults
  ufw: policy=deny logging=on

- name: Allow SSH
  ufw: rule=allow port=ssh proto=tcp

- name: Allow NTP
  ufw: rule=allow port=123 proto=udp

- name: Enable
  ufw: state=enabled
