---
- name: Install UFW
  tags: setup
  apt: name=ufw state=latest

- name: Reset UFW
  tags: config
  ufw: state=reset

- name: Configure defaults
  tags: config
  ufw: policy=deny logging=on

- name: Allow SSH
  tags: config
  ufw: rule=allow port=22 proto=tcp

- name: Allow NTP
  tags: config
  ufw: rule=allow port=123 proto=udp

- name: Allow public traffic
  tags: config
  ufw: rule=allow port={{item}} state=enabled proto=tcp
  with_items: firewall_allow_public_ports
  when: firewall_allow_public_ports

- name: Allow private traffic from db_clients group
  tags: config
  ufw: rule=allow port={{item.0}} from={{hostvars[item.1].private_ip}} state=enabled
  with_nested:
    - firewall_allow_private_ports
    - firewall_allow_db_clients
  when: firewall_allow_private_ports and firewall_allow_db_clients

- name: Allow private traffic from specified private ips
  tags: config
  ufw: rule=allow port={{item.0}} from={{item.1}}
  with_nested:
    - firewall_allow_private_ports
    - firewall_allow_private_ips
  when: firewall_allow_private_ports and firewall_allow_private_ips

- name: Enable
  tags: config
  ufw: state=enabled
