---
- name: Install Firewall (UFW)
  apt: name=ufw state=latest

- name: Set up firewall defaults
  ufw: state=enabled policy=deny logging=on

- name: Allow ports
  ufw: rule=allow port={{item}}
  with_items: {{firewall_allow_ports}}
