---
- name: 'Add app user'
  tags: setup
  user: name={{app_user}} shell=/bin/bash

- name: Verify authorized GitHub users are provided
  tags: setup
  fail: msg="app_authorized_githubbers must contain at least one GitHub username"
  when: not app_authorized_githubbers

- name: 'Download authorized keys from GitHub for app user'
  tags: ['config_ssh_keys', 'config']
  connection: local
  sudo: no
  get_url:
    url: https://github.com/{{item}}.keys
    dest: /tmp/github.{{item}}.keys
  with_items: app_authorized_githubbers

- name: 'Install authorized keys for {{app_user}}'
  tags: ['config_ssh_keys', 'config']
  authorized_key:
    user: '{{app_user}}'
    key: "{{lookup('file', '/tmp/github.' + item + '.keys')}}"
  with_items: app_authorized_githubbers

- name: Create root data directory
  tags: setup
  file: path={{app_data_directory}} state=directory

- name: Create application deploy tree (Capistrano)
  tags: setup
  file: 'path={{item}} state=directory owner={{app_user}} group={{app_group}}'
  with_items:
    - '{{app_directory}}'
    - '{{app_releases_directory}}'
    - '{{app_repo_directory}}'
    - '{{app_shared_directory}}'
    - '{{app_shared_log_directory}}'
    - '{{app_shared_tmp_directory}}'
    - '{{app_shared_config_directory}}'
    - '{{app_shared_bin_directory}}'
    - '{{app_shared_bundle_directory}}'
    - '{{app_shared_sockets_directory}}'

- name: Update database.yml
  tags: ['config_database_yml', 'config']
  template:
    src: database.yml.j2
    dest: '{{app_shared_config_directory}}/database.yml'
    owner: '{{app_user}}'
    group: '{{app_group}}'
    mode: '0640'

- name: Update secrets.yml
  tags: ['config_secrets_yml', 'config']
  template:
    src: secrets.yml.j2
    dest: '{{app_shared_config_directory}}/secrets.yml'
    owner: '{{app_user}}'
    group: '{{app_group}}'
    mode: '0640'
