---
- name: 'Add {{app_user}} user'
  user: name={{app_user}} shell=/bin/bash

- name: 'Download authorized keys from GitHub for {{app_user}}'
  connection: local
  get_url:
    url: https://github.com/{{item}}.keys
    dest: /tmp/github.{{item}}.keys
  with_items: app_authorized_githubbers

- name: 'Install authorized keys for {{app_user}}'
  authorized_key:
    user: '{{app_user}}'
    key: "{{lookup('file', '/tmp/github.' + item + '.keys')}}"
  with_items: app_authorized_githubbers

- name: Create root data directory
  file: path={{app_data_directory}} state=directory

- name: Create application deploy tree (Capistrano)
  file: 'path={{item}} state=directory owner={{app_user}}'
  with_items:
    - '{{app_directory}}'
    - '{{app_releases_directory}}'
    - '{{app_repo_directory}}'
    - '{{app_shared_directory}}'
    - '{{app_shared_log_directory}}'
    - '{{app_shared_tmp_directory}}'
    - '{{app_shared_config_directory}}'
    - '{{app_shared_bin_directory}}'
    - '{{app_shared_bundle_directory}}'
    - '{{app_shared_sockets_directory}}'
