---
redis_version: 2.8.13
redis_group: redis
redis_user: redis
redis_port: 6379
redis_databases: 16
redis_conf: /etc/redis.conf
redis_data_directory: /var/lib/redis
redis_data_file: dump.rdb
redis_log_directory: /var/log/redis
redis_log_file: redis.log

redis_logrotate_event: weekly
redis_logrotate_maxrotations: 52
