---
- name: Setting timezone in /etc/localtime to {{timezone}}
  copy: src=/usr/share/zoneinfo/{{timezone}} dest=/etc/localtime owner=root group=root mode=0644 backup=yes

- name: Setting timezone in /etc/timezone to {{timezone}}
  template: dest=/etc/timezone src=timezone.j2
  notify: Update tzdata
