---
- name: Provision a Vagrant VM with RVM, Redis, Postgres, Node, and Nginx
  hosts: localhost
  remote_user: vagrant
  gather_facts: False
  sudo: yes
  vars:
    - locale: en_US.UTF-8
    - rvm_ruby_version: 2.1.2
    - rvm_install_user: vagrant
    - vagrant_data: /vagrant
    - pg_version: 9.3

  roles:
    - essential_system
    - locale
    - timezone
    - ntp
    - rvm
    - nodejs
    - postgresql
    - redis
    - vagrant_system
