---
- name: Provision a Vagrant VM with RVM, Redis, Postgres, Node.js, and Nginx
  hosts: localhost
  remote_user: vagrant
  gather_facts: yes
  sudo: yes

  vars:
    - locale: en_US.UTF-8
    - rvm_ruby_version: 2.1.2
    - rvm_install_user: vagrant
    - postgresql_version: 9.3
    - vagrant_user: vagrant
    - vagrant_data_directory: /vagrant

  roles:
    - essential_system
    - locale
    - timezone
    - ntp
    - rvm
    - nodejs
    - postgresql
    - redis
    - nginx
    - vagrant_nginx
    - vagrant_postgresql
    - vagrant_helpful
