---
- name: Create state directory
  tags: setup
  file:
    path: '{{puma_state_directory}}'
    state: directory
    owner: '{{app_user}}'

- name: Add Upstart init config
  tags: setup
  template:
    src: upstart.conf.j2
    dest: /etc/init/{{puma_init_ident}}.conf
    owner: root
    group: root

- name: Add sudo entries for initctl
  tags: setup
  lineinfile:
    dest: /etc/sudoers
    line: '{{app_user}} ALL=NOPASSWD: /sbin/initctl {{item}} {{puma_init_ident}}'
    state: present
  with_items:
    - start
    - stop
    - reload
    - restart

- name: Add logrotate for application log
  tags: setup
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/{{puma_init_ident}}
    owner: root
    group: root
    mode: '0664'

- name: Add Nginx site
  tags: config
  template:
    src: nginx-site.j2
    dest: /etc/nginx/sites-available/{{app_domain}}
    owner: '{{nginx_user}}'
    group: '{{nginx_group}}'

- name: Enable Nginx site
  tags: config
  file:
    src: /etc/nginx/sites-available/{{app_domain}}
    path: /etc/nginx/sites-enabled/{{app_domain}}
    state: link
    owner: '{{nginx_user}}'
    group: '{{nginx_group}}'
  notify: Restart Nginx

- name: Enable Puma service
  tags: setup
  service: name={{puma_init_ident}} enabled=yes state=stopped
